apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devboard-admin-binding
  namespace: devboard
subjects:
  - kind: ServiceAccount
    name: devboard-admin
    namespace: devboard
roleRef:
  kind: Role
  name: devboard-admin
  apiGroup: rbac.authorization.k8s.io
