apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-immediate
  namespace: cka20
spec:
  storageClassName: bind-immediately
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 128Mi
