apiVersion: v1
kind: Service
metadata:
  name: devboard-frontend
  namespace: devboard
spec:
  type: NodePort
  selector:
    app: devboard-frontend
  ports:
    - name: http
      port: 80          # ClusterIP port -- NodePort is a superset of ClusterIP
      targetPort: http  # container port, by name
      nodePort: 30080   # MUST be 30000-32767, and to reach it from your browser
                        # it must be one of the ports mapped in
                        # cluster/kind-config.yaml (30080 and 30081 are)
  externalTrafficPolicy: Cluster
